### ISSUE TITLE
PMI crash

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/jitutils#147]
```
set complus_altjit=*
set complus_altjitname=protononjit.dll
F:\gh\coreclr10\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe c:\gh\jitutils\bin\PMI.dll prepall F:\gh\coreclr10\bin\tests\Windows_NT.x86.Checked\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b399444\b399444a\b399444a.exe
ReflectionTypeLoadException b399444a

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Worker.LoadTypes(Assembly assembly) in c:\gh\jitutils\src\pmi\pmi.cs:line 593
   at Worker.Work(String assemblyName) in c:\gh\jitutils\src\pmi\pmi.cs:line 704
   at PrepareMethodinator.Main(String[] args) in c:\gh\jitutils\src\pmi\pmi.cs:line 1095
```

In `LoadTypes(Assembly assembly)`:
```
        catch (ReflectionTypeLoadException e)
        {
            Console.WriteLine($"ReflectionTypeLoadException {assemblyName}");
            Exception[] ea = e.LoaderExceptions;
            foreach (Exception e2 in ea)
            {
                string[] ts = e2.ToString().Split('\'');
                string temp = ts[1];
                ts = temp.Split(',');
                temp = ts[0];
                Console.WriteLine($"ReflectionTypeLoadException {assemblyName}   ex: {e2.Message}");
            }
```
it looks like ts and temp are unused. But in this case, ts[] is length 1 and ts[0] is "System.TypeLoadException: Internal limitation: too many fields."

**Comment by BruceForstall** [comment]
@AndyAyersMS
