### ISSUE TITLE
crossgen diffs broken

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/jitutils#211]
Not sure when I last ran this, but it wasn't all that long ago. So this seems like a recent behavior change.

cc @dotnet/jit-contrib 

crossgen jit-diffs will run both base and diff concurrently, but the crossgen outputs should be going to distinct directories and shouldn't collide with each other, or get pulled into any other running process.
```
D:\repos\coreclr>jit-diff diff --base --base_root d:\repos\coreclr2 --diff -f
Using --output D:\repos\coreclr\bin\diffs
Using --base d:\repos\coreclr2\bin\Product\Windows_NT.x64.Checked
Using --diff D:\repos\coreclr\bin\Product\Windows_NT.x64.Checked
Using --arch x64
Using --core_root D:\repos\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root
Beginning Crossgen Diffs for System.Private.CoreLib.dll, framework assemblies
\ Finished 125/129 Base 111/129 Diff [135.8 sec]Unhandled Exception: System.IO.IOException: The process cannot access the file 'D:\repos\coreclr\bin\diffs\dasmset_3\base\NuGet.DependencyResolver.Core.ni.dll' because it is being used by another process.
Unhandled Exception: System.IO.IOException: The process cannot access the file 'D:\repos\coreclr\bin\diffs\dasmset_3\base\System.IO.FileSystem.Watcher.ni.dll' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at ManagedCodeGen.jitdasm.DisasmEngine.GenerateAsm() in D:\repos\jitutils\src\jit-dasm\jit-dasm.cs:line 569
Unhandled Exception: System.IO.IOException: The process cannot access the file 'D:\repos\coreclr\bin\diffs\dasmset_3\diff\System.Threading.Thread.ni.dll' because it is being used by another process.
   at ManagedCodeGen.jitdasm.Main(String[] args) in D:\repos\jitutils\src\jit-dasm\jit-dasm.cs:line 193- Finished 126/129 Base 122/129 Diff [136.0 sec]
   at System.IO.File.Delete(String path)[] args) in D:\repos\jitutils\src\jit-dasm\jit-dasm.cs:line 193
   at ManagedCodeGen.jitdasm.DisasmEngine.GenerateAsm() in D:\repos\jitutils\src\jit-dasm\jit-dasm.cs:line 569
   at ManagedCodeGen.jitdasm.Main(String[] args) in D:\repos\jitutils\src\jit-dasm\jit-dasm.cs:line 193
```

**Comment by BruceForstall** [comment]
@AndyAyersMS Anti-virus?

You could run it in verbose mode to see all the actual command lines to see if any refer to the same file from different commands.

**Comment by AndyAyersMS** [comment]
Haven't seen this again, so will close.
