### ISSUE TITLE
jit-diff fails with "Cannot set initonly static field ..."

### ISSUE THREAD

**Issue by tannergooding** [dotnet/jitutils#271]
Running a jit-diff, such as `..\jitutils\bin\jit-diff.bat diff --diff --pmi --benchmarks`, currently fails with an error similar to the following:

```
Unhandled exception. System.FieldAccessException: Cannot set initonly static field 's_isProcessorNumberReallyFast' after type 'System.Threading.Thread' is initialized.
   at System.RuntimeFieldHandle.SetValue(RtFieldInfo field, Object obj, Object value, RuntimeType fieldType, FieldAttributes fieldAttr, RuntimeType declaringType, Boolean& domainInitialized)
   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at System.Reflection.FieldInfo.SetValue(Object obj, Object value)
   at PrepareMethodinator.EnsureGetCurrentProcessorIdIsDeterministic() in D:\tagoo\Repos\jitutils\src\pmi\pmi.cs:line 1332
   at PrepareMethodinator.Main(String[] args) in D:\tagoo\Repos\jitutils\src\pmi\pmi.cs:line 1363
```

**Comment by tannergooding** [comment]
CC. @erozenfeld, it looks like this was added in https://github.com/dotnet/jitutils/pull/255

**Comment by erozenfeld** [comment]
Yes, I’ll need to tweak this workaround. Will take a look today.
