### ISSUE TITLE
jit-format crashes given bad --coreclr path

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/jitutils#63]
e.g.:
```
D:\gh\coreclr3>jit-format -a x86 -o Windows -b Debug -c d:\gh\corclr3

Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at ManagedCodeGen.jitformat.TryCommand(String name, IEnumerable`1 commandArgs, Boolean capture)
   at ManagedCodeGen.jitformat.Config.validate()
   at ManagedCodeGen.jitformat.Main(String[] args)
```

That's not a helpful error message. It should check for existing path.

**Comment by BruceForstall** [comment]
@adiaaida @RussKeldorph
