### ISSUE TITLE
Running `jit-diff diff` crashes

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/jitutils#80]
```
c:\gh\coreclr>jit-diff diff
Environment variable JIT_UTILS_ROOT not found - no configuration loaded.

Unhandled Exception: System.MissingMethodException: Method not found: 'Microsoft.DotNet.Cli.Utils.Command Microsoft.DotNet.Cli.Utils.Command.Create(System.String, System.Collections.Generic.IEnumerable`1<System.String>, NuGet.Frameworks.NuGetFramework)'.
   at ManagedCodeGen.jitdiff.TryCommand(String name, IEnumerable`1 commandArgs, Boolean capture)
   at ManagedCodeGen.jitdiff.Config.SetRID()
   at ManagedCodeGen.jitdiff.Config..ctor(String[] args)
   at ManagedCodeGen.jitdiff.Main(String[] args)
```

Maybe this should output the "help" screen, but it shouldn't crash.

**Comment by mikedn** [comment]
I think I ran into this before. The project.json files used by jit utils reference different versions of some assemblies and all projects output to the same bin directory. So we end up with executables that were compiled against some assembly version X running against assembly version Y.
